### ISSUE TITLE
error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by dmd** [kkoomen/qbr#25]
I get:

```
dmd@atto …/qbr on  master via 🐍 v3.9.6 (env) took 14s
✖1 ❯ ./src/qbr.py
Traceback (most recent call last):
  File "/Users/dmd/qbr/./src/qbr.py", line 82, in <module>
    Qbr(args.normalize).run()
  File "/Users/dmd/qbr/./src/qbr.py", line 38, in run
    state = webcam.run()
  File "/Users/dmd/qbr/src/video.py", line 477, in run
    grayFrame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.1) /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-req-build-p3unqtkr/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by dmd** [comment]
I tried this on a Macbook Pro (intel) and an iMac (M1). Both have working webcams in the sense of "Zoom works", but I've not previously tried OpenCV with them. I'll see if I can get OpenCV to open the webcam in other contexts.

**Comment by dmd** [comment]
In any event though I agree that this has something to do with opencv doing something weird on my end, and nothing to do with your package, so this is up to me to debug.
